# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-15 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('type1', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='location',
            new_name='lati',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='password',
            new_name='lid',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='username',
            new_name='longi',
        ),
        migrations.AddField(
            model_name='shop',
            name='status',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
