# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-15 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210115_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='lid',
        ),
        migrations.AddField(
            model_name='login',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
