# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-16 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210115_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_center',
            fields=[
                ('reg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lid', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('longi', models.CharField(max_length=200)),
                ('lati', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('status', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('reg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lid', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('status', models.CharField(default=0, max_length=200)),
            ],
        ),
    ]
