# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-16 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='lati',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='longi',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.CharField(max_length=200),
        ),
    ]
