# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-16 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20210116_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='latitude',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shop',
            name='longitude',
            field=models.FloatField(max_length=200),
        ),
    ]
