# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-16 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20210116_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('feedback', models.CharField(max_length=200)),
                ('lid', models.IntegerField()),
                ('pro_id', models.IntegerField()),
                ('sentiment', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='r_status',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
