# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-05-29 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_trouble'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_center',
            name='lati',
        ),
        migrations.RemoveField(
            model_name='service_center',
            name='longi',
        ),
        migrations.AddField(
            model_name='service_center',
            name='latitude',
            field=models.FloatField(default=9.9930384, max_length=200),
        ),
        migrations.AddField(
            model_name='service_center',
            name='longitude',
            field=models.FloatField(default=76.2971463, max_length=200),
        ),
    ]
