# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-05-30 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='uid',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
